### ISSUE TITLE
Please remove optional wrappers from required dependencies

### ISSUE THREAD

**Issue by MrPetovan** [byjg/anydataset#7]
Hi,

I'm using this library through `byjg/migration` but I'm not using the AWS nor the SparQL wrapper, is it possible to move these dependencies to `suggest` instead of `require`?

Thanks!

**Comment by byjg** [comment]
Let me check and then I'll return to you.

**Comment by byjg** [comment]
Hello, 

I removed the dependencies and put in a new branch - `3.0.6`. Right now if in your composer file you define `"minimum-stability": "dev",`  you can get this new version. 

I wont generate a new tag right now, because I want to refactory this project in several projects (one for Relational, other for Non-Relational, Other for Text Manipulation, SparQl and so on). Probably this weekend I'll start doing this. 

Let me know if this helps you.

**Comment by byjg** [comment]
Is that worked?

**Comment by MrPetovan** [comment]
I didn't try yet, sorry, I will tonight, thanks for your work!

**Comment by MrPetovan** [comment]
I finally tried, and just adding `"minimum-stability": "dev"` didn't do the trick in my project, I'm still using `byjg/anydataset` version 3.0.5 because I'm requiring `byjg/migration:^2.1`.

Instead I tried creating a Composer project from scratch, and specifying `"minimum-stability": "dev"` before `composer require byjg/migration` selects the `dev-master` version and correctly loads `byjg-migration:3.0.6.x-dev`. I can verify that `byjg/sparqllib` and `aws/aws-sdk-php` are now in the suggestions.

**Comment by MrPetovan** [comment]
Interesting, thank you for your work!

**Comment by byjg** [comment]
Hello, I upgraded all packages. 

Please upgrade your migration version to `4.0.*`. Will have less packages installed.

**Comment by MrPetovan** [comment]
Thank you so much!
